import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { FireGraphDto, FireTableDto } from "../../apiClients/firestone.generated";
import { firestoneService } from "../../services/firestoneService";
import styles from "../../styles/Home.module.css";

const Table: NextPage = () => {
  const router = useRouter();
  const { tableid } = router.query;

  const [table, setTable] = useState<FireTableDto>();
  const [graph, setGraph] = useState<FireGraphDto>();
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const getTable = async () => {
      const table = await firestoneService.tables().get(tableid as string);
      const graph = await firestoneService.graphs().get(tableid as string);

      setTable(table);
      setGraph(graph);
      setLoading(false);
    };

    getTable();
  }, [tableid]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>{tableid}</div>
        <pre>{JSON.stringify(table, null, 2)}</pre>
        <pre>{JSON.stringify(graph, null, 2)}</pre>
      </main>
    </div>
  );
};

export default Table;
