import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import { firestoneService } from "../services/firestoneService";
import { FireTableSummaryDto } from "../apiClients/firestone.generated";
import Link from "next/link";

const Home: NextPage = () => {
  const [tables, setTables] = useState<FireTableSummaryDto[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const getTables = async () => {
      const tables = await firestoneService.tables().list();
      setTables(tables.results ?? []);
      setLoading(false);
    };

    getTables();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {loading ? (
          <div>Loading...</div>
        ) : (
          <table>
            <th>
              <td>AssetHolders</td>
            </th>
            {tables.map((table, index) => (
              <tr key={index}>
                <Link href={{ pathname: "/tables/[tableid]", query: { tableid: table.id } }}>
                  <a>
                    <td>
                      {table.assetHolders?.map((assetHolder, index) => (
                        <span key={index}>{assetHolder.name}</span>
                      ))}
                    </td>
                  </a>
                </Link>
              </tr>
            ))}
          </table>
        )}
      </main>

      <footer className={styles.footer}>
        <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home
